[communication]
multiplexer_addr = "Default"
multiplexer_bus = "i2c4"
sensor_addr = 0x68

[accelerometer]
scale = 0

[gyroscope]
scale = 0

[pose]
s2f = [
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]]
origin_f = [-0.01,0.0,-0.0460]